image: python:3.10

stages:
  - Type Checking
  - Lint
  - Formatting

before_script:
  - python -m pip install --upgrade pip
  - python install_requirements.py

mypy:
  stage: Type Checking
  script:
    - mypy .

ruff:
  stage: Lint
  script:
    - ruff --show-source .

black:
  stage: Formatting
  script:
    - black --check --diff .

isort:
  stage: Formatting
  script:
    - isort --check --diff .
